### ISSUE TITLE
dashboard user

### ISSUE THREAD

**Issue by nazwaseptyas** [FE-14-Skilvul/BrainerEdu#2]
<img width="533" alt="Jepretan Layar 2023-05-02 pukul 15 03 08" src="https://user-images.githubusercontent.com/95213063/235612314-e6b1568d-7b2b-4e37-aa42-ee266164cfdd.png">

**Comment by Aryawardhanaa** [comment]
https://drive.google.com/file/d/15m-SODk-UC7GFxScDk-Z5ELuZET5dGX0/view?usp=share_link
